<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class SurveyMeasureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('survey_measures')->insert([
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 3,
                'measure_title' => '社内候補紙に掲載する',
                'measure_description' => '企業の社会的責任（CSR）に関する活動内容を、社内広報誌を通じて全社員に共有。取り組みの認知度向上と社員の意識醸成を図ることを目的とした施策です。',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施済み',
                'start_date' => Carbon::now()->subDays(30),
                'end_date' => Carbon::now()->subDays(10),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(30),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '上司向けコーチング型マネジメント研修の導入',
                'measure_description' => '部下育成への意識と具体的支援スキルを高めるため、上司向けにコーチング手法や成長支援の考え方を学ぶ研修を実施。支援行動の定着を図ります。',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施済み',
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->subDays(15),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(30),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 15,
                'measure_title' => '会社の将来計画をわかりやすく伝える説明会の実施',
                'measure_description' => '施策の詳細説明 1',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施済み',
                'start_date' => Carbon::now()->subDays(70),
                'end_date' => Carbon::now()->subDays(10),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(30),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '現場の声をもとに未来の計画を見直す仕組みづくり',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '若手社員が未来のアイデアを出せる場の提供',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => 'チームごとに未来の目標を話し合う時間を設ける',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '会社の進む方向を動画でわかりやすく説明',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ], [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '未来の目標に向けた社員の取り組みを紹介する社内イベント',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '会社の方向性についてアンケートを実施して改善に活かす',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ], [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '将来の計画が日々の仕事とどうつながるかを説明する場の設置',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '経営陣と社員の対話の場を定期的に設ける',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ], [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '未来に向けた成功事例を共有する社内勉強会',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '経営陣と社員の対話の場を定期的に設ける',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '会社の将来計画をわかりやすく伝える説明会の実施',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '会社の将来計画をわかりやすく伝える説明会の実施',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ], [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '若手社員が未来のアイデアを出せる場の提供',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
            [
                'survey_id' => 1,
                'company_id' => 1,
                'organization_hierarchy_id' => 2,
                'organization_names_id' => 2,
                'question_id' => 12,
                'measure_title' => '経営陣と社員の対話の場を定期的に設ける',
                'measure_description' => '施策の詳細説明 2',
                'target_scope' => '部門全体',
                'user_id' => 1,
                'status' => '実施中',
                'start_date' => Carbon::now()->subDays(110),
                'end_date' => Carbon::now()->addDays(100),
                'measure_effect' => null,
                'created_at' => Carbon::now()->subDays(100),
                'updated_at' => Carbon::now()->subDays(100),
            ],
        ]);
    }
}
